# Generated by Django 4.2.7 on 2026-06-08 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_alter_loaninstallmentschedule_loan'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCollectionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('verified', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('loan', 'Loan Installment'), ('savings', 'Savings Deposit'), ('fee', 'Processing Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.TextField(blank=True)),
                ('loan_installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loaninstallmentschedule')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.member')),
                ('savings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='savings.savingsaccount')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='collections.dailycollectionsheet')),
            ],
        ),
    ]
