# Generated by Django 4.2.7 on 2026-06-11 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionentry',
            options={'permissions': [('can_change_collectionentry', 'Can edit collection entries'), ('can_delete_collectionentry', 'Can delete collection entries')]},
        ),
        migrations.AlterModelOptions(
            name='dailycollectionsheet',
            options={'permissions': [('can_verify_collectionsheet', 'Can verify collection sheets')]},
        ),
        migrations.AddField(
            model_name='dailycollectionsheet',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailycollectionsheet',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
