# Generated by Django 4.2.7 on 2026-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url_name', models.CharField(max_length=200, unique=True)),
                ('path', models.CharField(blank=True, help_text='Optional display path for the URL', max_length=300)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Allowed URL',
                'verbose_name_plural': 'Allowed URLs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_urls',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.allowedurl'),
        ),
    ]
